# Generated by Django 4.1 on 2022-11-07 21:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_alter_task_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('group', 'title')},
        ),
    ]
